application: sann-tid
version: v2-0-2
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "10d"

handlers:
- url: /favicon.ico
  static_files: html/images/favicon.ico
  upload: html/images/favicon.ico

- url: /css
  static_dir: html/css

- url: /app
  static_dir: html/app

- url: /partials
  static_dir: html/partials

- url: /images
  static_dir: html/images

- url: /
  static_files: html/index.html
  upload: html/index.html

skip_files:
- node_modules/.*
- .git/.*
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
